FROM node:18-alpine as builder

WORKDIR /usr/src/app

COPY package.json ./

RUN npm install --force

COPY . .

RUN npm run build

FROM node:18-alpine

WORKDIR /usr/src/app

RUN npm install -g serve

COPY --from=builder /usr/src/app/build /usr/src/app/build

EXPOSE 5000

CMD ["serve", "-s", "build", "-l", "5000"]
