version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile_dev
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
